{$ifdef license}
(*
  Copyright 2020 ChapmanWorld LLC ( https://chapmanworld.com )

  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation and/or
     other materials provided with the distribution.

  3. Neither the name of the copyright holder nor the names of its contributors may be
     used to endorse or promote products derived from this software without specific prior
     written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
  FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
  IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*)
{$endif}
unit cwWin32.User32;

interface
{$ifdef MSWINDOWS}
uses
  cwWin32.Types
;

const
  cLibName = 'user32.dll';

function ActivateKeyboardLayout(hkl: THKL; Flags: UINT): THKL; stdcall; external cLibName name 'ActivateKeyboardLayout';
function AdjustWindowRect(var lpRect: TRect; dwStyle: DWORD; bMenu: BOOL): BOOL; stdcall; external cLibName name 'AdjustWindowRect';
function AdjustWindowRectEx(var lpRect: TRect; dwStyle: DWORD; bMenu: BOOL; dwExStyle: DWORD): BOOL; stdcall; external cLibName name 'AdjustWindowRectEx';
function AnimateWindow(hWnd: THWND; dwTime: DWORD; dwFlags: DWORD): BOOL; stdcall; external cLibName name 'AnimateWindow';
function AnyPopup: BOOL; stdcall; external cLibName name 'AnyPopup';
function AppendMenu(hMenu: THMENU; uFlags, uIDNewItem: UINT; lpNewItem: PAnsiChar): BOOL; stdcall; external cLibName name 'AppendMenuA';
function AppendMenuW(hMenu: THMENU; uFlags, uIDNewItem: UINT; lpNewItem: PWideChar): BOOL; stdcall; external cLibName name 'AppendMenuW';
function ArrangeIconicWindows(hWnd: THWND): UINT; stdcall; external cLibName name 'ArrangeIconicWindows';
function AttachThreadInput(idAttach, idAttachTo: DWORD; fAttach: BOOL): BOOL; stdcall; external cLibName name 'AttachThreadInput';
function BeginDeferWindowPos(nNumWindows: Integer): THDWP; stdcall; external cLibName name 'BeginDeferWindowPos';
function BeginPaint(hWnd: THWND; var lpPaint: TPaintStruct): THDC; stdcall; external cLibName name 'BeginPaint';
function BringWindowToTop(hWnd: THWND): BOOL; stdcall; external cLibName name 'BringWindowToTop';
function BroadcastSystemMessage(Flags: DWORD; Recipients: PDWORD; uiMessage: UINT; wParam: TWPARAM; lParam: TLPARAM): Longint; stdcall; external cLibName name 'BroadcastSystemMessage';
function CallMsgFilter(var lpMsg: TMsg; nCode: Integer): BOOL; stdcall; external cLibName name 'CallMsgFilterA';
function CallMsgFilterW(var lpMsg: TMsg; nCode: Integer): BOOL; stdcall; external cLibName name 'CallMsgFilterW';
function CallNextHookEx(hhk: THHOOK; nCode: Integer; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'CallNextHookEx';
function CallWindowProc(lpPrevWndFunc: TWndProc; hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'CallWindowProcA';
function CallWindowProcW(lpPrevWndFunc: TWndProc; hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'CallWindowProcW';
function CascadeWindows(hwndParent: THWND; wHow: UINT; lpRect: PRect; cKids: UINT; lpKids: Pointer): Word; stdcall; external cLibName name 'CascadeWindows';
function ChangeClipboardChain(hWndRemove, hWndNewNext: THWND): BOOL; stdcall; external cLibName name 'ChangeClipboardChain';
function ChangeDisplaySettings(var lpDevMode: TDeviceModeA; dwFlags: DWORD): Longint; stdcall; external cLibName name 'ChangeDisplaySettingsA';
function ChangeDisplaySettingsEx(lpszDeviceName: PAnsiChar; var lpDevMode: TDeviceModeA; wnd: THWND; dwFlags: DWORD; lParam: Pointer): Longint; stdcall; external cLibName name 'ChangeDisplaySettingsExA';
function ChangeDisplaySettingsExW(lpszDeviceName: PWideChar; var lpDevMode: TDeviceModeW; wnd: THWND; dwFlags: DWORD; lParam: Pointer): Longint; stdcall; external cLibName name 'ChangeDisplaySettingsExW';
function ChangeDisplaySettingsW(var lpDevMode: TDeviceModeW; dwFlags: DWORD): Longint; stdcall; external cLibName name 'ChangeDisplaySettingsW';
function ChangeMenu(hMenu: THMENU; cmd: UINT; lpszNewItem: PAnsiChar; cmdInsert: UINT; flags: UINT): BOOL; stdcall; external cLibName name 'ChangeMenuA';
function ChangeMenuW(hMenu: THMENU; cmd: UINT; lpszNewItem: PWideChar; cmdInsert: UINT; flags: UINT): BOOL; stdcall; external cLibName name 'ChangeMenuW';
function CharLower(lpsz: PAnsiChar): PAnsiChar; stdcall; external cLibName name 'CharLowerA';
function CharLowerBuff(lpsz: PAnsiChar; cchLength: DWORD): DWORD; stdcall; external cLibName name 'CharLowerBuffA';
function CharLowerBuffW(lpsz: PWideChar; cchLength: DWORD): DWORD; stdcall; external cLibName name 'CharLowerBuffW';
function CharLowerW(lpsz: PWideChar): PWideChar; stdcall; external cLibName name 'CharLowerW';
function CharNext(lpsz: PAnsiChar): PAnsiChar; stdcall; external cLibName name 'CharNextA';
function CharNextEx(CodePage: Word; lpCurrentChar: LPCSTR; dwFlags: DWORD): LPSTR; stdcall; external cLibName name 'CharNextExA';
function CharNextW(lpsz: PWideChar): PWideChar; stdcall; external cLibName name 'CharNextW';
function CharPrev(lpszStart: PAnsiChar; lpszCurrent: PAnsiChar): PAnsiChar; stdcall; external cLibName name 'CharPrevA';
function CharPrevEx(CodePage: Word; lpStart, lpCurrentChar: LPCSTR; dwFlags: DWORD): LPSTR; stdcall; external cLibName name 'CharPrevExA';
function CharPrevW(lpszStart: PWideChar; lpszCurrent: PWideChar): PWideChar; stdcall; external cLibName name 'CharPrevW';
function CharToOem(lpszSrc: PAnsiChar; lpszDst: PAnsiChar): BOOL; stdcall; external cLibName name 'CharToOemA';
function CharToOemBuff(lpszSrc: PAnsiChar; lpszDst: PAnsiChar; cchDstLength: DWORD): BOOL; stdcall; external cLibName name 'CharToOemBuffA';
function CharToOemBuffW(lpszSrc: PWideChar; lpszDst: PWideChar; cchDstLength: DWORD): BOOL; stdcall; external cLibName name 'CharToOemBuffW';
function CharToOemW(lpszSrc: PWideChar; lpszDst: PWideChar): BOOL; stdcall; external cLibName name 'CharToOemW';
function CharUpper(lpsz: PAnsiChar): PAnsiChar; stdcall; external cLibName name 'CharUpperA';
function CharUpperBuff(lpsz: PAnsiChar; cchLength: DWORD): DWORD; stdcall; external cLibName name 'CharUpperBuffA';
function CharUpperBuffW(lpsz: PWideChar; cchLength: DWORD): DWORD; stdcall; external cLibName name 'CharUpperBuffW';
function CharUpperW(lpsz: PWideChar): PWideChar; stdcall; external cLibName name 'CharUpperW';
function CheckDlgButton(hDlg: THWND; nIDButton: Integer; uCheck: UINT): BOOL; stdcall; external cLibName name 'CheckDlgButton';
function CheckMenuItem(hMenu: THMENU; uIDCheckItem, uCheck: UINT): DWORD; stdcall; external cLibName name 'CheckMenuItem';
function CheckMenuRadioItem(hMenu: THMENU; First, Last, Check, Flags: UINT): BOOL; stdcall; external cLibName name 'CheckMenuRadioItem';
function CheckRadioButton(hDlg: THWND; nIDFirstButton, nIDLastButton, nIDCheckButton: Integer): BOOL; stdcall; external cLibName name 'CheckRadioButton';
function ChildWindowFromPoint(hWndParent: THWND; Point: TPoint): THWND; stdcall; external cLibName name 'ChildWindowFromPoint';
function ChildWindowFromPointEx(hWnd: THWND; Point: TPoint; Flags: UINT): THWND; stdcall; external cLibName name 'ChildWindowFromPointEx';
function ClientToScreen(hWnd: THWND; var lpPoint: TPoint): BOOL; stdcall; external cLibName name 'ClientToScreen';
function ClipCursor(lpRect: PRect): BOOL; stdcall; external cLibName name 'ClipCursor';
function CloseClipboard: BOOL; stdcall; external cLibName name 'CloseClipboard';
function CloseDesktop(hDesktop: THDESK): BOOL; stdcall; external cLibName name 'CloseDesktop';
function CloseWindow(hWnd: THWND): BOOL; stdcall; external cLibName name 'CloseWindow';
function CloseWindowStation(hWinSta: THWINSTA): BOOL; stdcall; external cLibName name 'CloseWindowStation';
function CopyAcceleratorTable(hAccelSrc: THACCEL; var lpAccelDst; cAccelEntries: Integer): Integer; stdcall; external cLibName name 'CopyAcceleratorTableA';
function CopyAcceleratorTableW(hAccelSrc: THACCEL; var lpAccelDst; cAccelEntries: Integer): Integer; stdcall; external cLibName name 'CopyAcceleratorTableW';
function CopyIcon(hIcon: THICON): THICON; stdcall; external cLibName name 'CopyIcon';
function CopyImage(hImage: THandle; ImageType: UINT; X, Y: Integer; Flags: UINT): THandle; stdcall; external cLibName name 'CopyImage';
function CopyRect(var lprcDst: TRect; const lprcSrc: TRect): BOOL; stdcall; external cLibName name 'CopyRect';
function CountClipboardFormats: Integer; stdcall; external cLibName name 'CountClipboardFormats';
function CreateAcceleratorTable(var Accel; Count: Integer): THACCEL; stdcall; external cLibName name 'CreateAcceleratorTableA';
function CreateAcceleratorTableW(var Accel; Count: Integer): THACCEL; stdcall; external cLibName name 'CreateAcceleratorTableW';
function CreateCaret(hWnd: THWND; hBitmap: THBITMAP; nWidth, nHeight: Integer): BOOL; stdcall; external cLibName name 'CreateCaret';
function CreateCursor(hInst: THINST; xHotSpot, yHotSpot, nWidth, nHeight: Integer; pvANDPlaneter, pvXORPlane: Pointer): THCURSOR; stdcall; external cLibName name 'CreateCursor';
function CreateDesktop(lpszDesktop, lpszDevice: PAnsiChar; pDevmode: PDeviceModeA; dwFlags: DWORD; dwDesiredAccess: DWORD; lpsa: PSecurityAttributes): THDESK; stdcall; external cLibName name 'CreateDesktopA';
function CreateDesktopW(lpszDesktop, lpszDevice: PWideChar; pDevmode: PDeviceModeW; dwFlags: DWORD; dwDesiredAccess: DWORD; lpsa: PSecurityAttributes): THDESK; stdcall; external cLibName name 'CreateDesktopW';
function CreateDialogIndirectParam(hInstance: THINST; const lpTemplate: TDlgTemplate; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): THWND; stdcall; external cLibName name 'CreateDialogIndirectParamA';
function CreateDialogIndirectParamW(hInstance: THINST; const lpTemplate: TDlgTemplate; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): THWND; stdcall; external cLibName name 'CreateDialogIndirectParamW';
function CreateDialogParam(hInstance: THINST; lpTemplateName: PAnsiChar; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): THWND; stdcall; external cLibName name 'CreateDialogParamA';
function CreateDialogParamW(hInstance: THINST; lpTemplateName: PWideChar; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): THWND; stdcall; external cLibName name 'CreateDialogParamW';
function CreateIcon(hInstance: THINST; nWidth, nHeight: Integer; cPlanes, cBitsPixel: Byte; lpbANDbits, lpbXORbits: Pointer): THICON; stdcall; external cLibName name 'CreateIcon';
function CreateIconFromResource(presbits: PByte; dwResSize: DWORD; fIcon: BOOL; dwVer: DWORD): THICON; stdcall; external cLibName name 'CreateIconFromResource';
function CreateIconFromResourceEx(presbits: PByte; dwResSize: DWORD; fIcon: BOOL; dwVer: DWORD; cxDesired, cyDesired: Integer; Flags: UINT): THICON; stdcall; external cLibName name 'CreateIconFromResourceEx';
function CreateIconIndirect(var piconinfo: TIconInfo): THICON; stdcall; external cLibName name 'CreateIconIndirect';
function CreateMDIWindow(lpClassName, lpWindowName: PAnsiChar; dwStyle: DWORD; X, Y, nWidth, nHeight: Integer; hWndParent: THWND; hInstance: THINST; lParam: TLPARAM): THWND; stdcall; external cLibName name 'CreateMDIWindowA';
function CreateMDIWindowW(lpClassName, lpWindowName: PWideChar; dwStyle: DWORD; X, Y, nWidth, nHeight: Integer; hWndParent: THWND; hInstance: THINST; lParam: TLPARAM): THWND; stdcall; external cLibName name 'CreateMDIWindowW';
function CreateMenu: THMENU; stdcall; external cLibName name 'CreateMenu';
function CreatePopupMenu: THMENU; stdcall; external cLibName name 'CreatePopupMenu';
function CreateWindowEx(dwExStyle: DWORD; lpClassName: PAnsiChar; lpWindowName: PAnsiChar; dwStyle: DWORD; X, Y, nWidth, nHeight: Integer; hWndParent: THWND; hMenu: THMENU; hInstance: THINST; lpParam: Pointer): THWND; stdcall; external cLibName name 'CreateWindowExA';
function CreateWindowExW(dwExStyle: DWORD; lpClassName: PWideChar; lpWindowName: PWideChar; dwStyle: DWORD; X, Y, nWidth, nHeight: Integer; hWndParent: THWND; hMenu: THMENU; hInstance: THINST; lpParam: Pointer): THWND; stdcall; external cLibName name 'CreateWindowExW';
function CreateWindowStation(lpwinsta: PAnsiChar; dwReserved, dwDesiredAccess: DWORD; lpsa: PSecurityAttributes): THWINSTA; stdcall; external cLibName name 'CreateWindowStationA';
function CreateWindowStationW(lpwinsta: PWideChar; dwReserved, dwDesiredAccess: DWORD; lpsa: PSecurityAttributes): THWINSTA; stdcall; external cLibName name 'CreateWindowStationW';
function DdeAbandonTransaction(Inst: DWORD; Conv: THConv; Transaction: DWORD): BOOL; stdcall; external cLibName name 'DdeAbandonTransaction';
function DdeAccessData(Data: THDDEData; DataSize: PDWORD): Pointer; stdcall; external cLibName name 'DdeAccessData';
function DdeAddData(Data: THDDEData; Src: Pointer; cb, Off: DWORD): THDDEData; stdcall; external cLibName name 'DdeAddData';
function DdeClientTransaction(Data: Pointer; DataLen: DWORD; Conv: THConv; Item: THSZ; Fmt, DataType: UINT; Timeout: DWORD; Result: PDWORD): THDDEData; stdcall; external cLibName name 'DdeClientTransaction';
function DdeCmpStringHandles(hsz1, hsz2: THSZ): Integer; stdcall; external cLibName name 'DdeCmpStringHandles';
function DdeConnect(Inst: DWORD; Service, Topic: THSZ; CC: PConvContext): THConv; stdcall; external cLibName name 'DdeConnect';
function DdeConnectList(Inst: DWORD; Service, Topic: THSZ; ConvList: THConvList; CC: PConvContext): THConvList; stdcall; external cLibName name 'DdeConnectList';
function DdeCreateDataHandle(Inst: DWORD; Src: Pointer; cb, Off: DWORD; Item: THSZ; Fmt, Cmd: UINT): THDDEData; stdcall; external cLibName name 'DdeCreateDataHandle';
function DdeCreateStringHandle(Inst: DWORD; psz: PAnsiChar; CodePage: Integer): THSZ; stdcall; external cLibName name 'DdeCreateStringHandleA';
function DdeCreateStringHandleW(Inst: DWORD; psz: PWideChar; CodePage: Integer): THSZ; stdcall; external cLibName name 'DdeCreateStringHandleW';
function DdeDisconnect(Conv: THConv): BOOL; stdcall; external cLibName name 'DdeDisconnect';
function DdeDisconnectList(ConvList: THConvList): BOOL; stdcall; external cLibName name 'DdeDisconnectList';
function DdeEnableCallback(Inst: DWORD; Conv: THConv; Cmd: UINT): BOOL; stdcall; external cLibName name 'DdeEnableCallback';
function DdeFreeDataHandle(Data: THDDEData): BOOL; stdcall; external cLibName name 'DdeFreeDataHandle';
function DdeFreeStringHandle(Inst: DWORD; HSZ: THSZ): BOOL; stdcall; external cLibName name 'DdeFreeStringHandle';
function DdeGetData(Data: THDDEData; Dst: Pointer; Max, Off: DWORD): DWORD; stdcall; external cLibName name 'DdeGetData';
function DdeGetLastError(Inst: DWORD): UINT; stdcall; external cLibName name 'DdeGetLastError';
function DdeInitialize(var Inst: Longint; Callback: TDDECallback; Cmd, Res: Longint): Longint; stdcall; external cLibName name 'DdeInitializeA';
function DdeInitializeW(var Inst: Longint; Callback: TDDECallback; Cmd, Res: Longint): Longint; stdcall; external cLibName name 'DdeInitializeW';
function DdeKeepStringHandle(Inst: DWORD; HSZ: THSZ): BOOL; stdcall; external cLibName name 'DdeKeepStringHandle';
function DdeNameService(Inst: DWORD; hsz1, hsz2: THSZ; Cmd: UINT): THDDEData; stdcall; external cLibName name 'DdeNameService';
function DdePostAdvise(Inst: DWORD; Topic, Item: THSZ): BOOL; stdcall; external cLibName name 'DdePostAdvise';
function DdeQueryConvInfo(Conv: THConv; Transaction: DWORD; ConvInfo: PConvInfo): UINT; stdcall; external cLibName name 'DdeQueryConvInfo';
function DdeQueryNextServer(ConvList: THConvList; ConvPrev: THConv): THConv; stdcall; external cLibName name 'DdeQueryNextServer';
function DdeQueryString(Inst: DWORD; HSZ: THSZ; psz: PAnsiChar; Max: DWORD; CodePage: Integer): DWORD; stdcall; external cLibName name 'DdeQueryStringA';
function DdeQueryStringW(Inst: DWORD; HSZ: THSZ; psz: PWideChar; Max: DWORD; CodePage: Integer): DWORD; stdcall; external cLibName name 'DdeQueryStringW';
function DdeReconnect(Conv: THConv): THConv; stdcall; external cLibName name 'DdeReconnect';
function DdeSetQualityOfService(hWndClient: THWnd; const pqosNew: TSECURITY_QUALITY_OF_SERVICE; pqosPrev: PSECURITY_QUALITY_OF_SERVICE): BOOL; stdcall; external cLibName name 'DdeSetQualityOfService';
function DdeSetUserHandle(Conv: THConv; ID, User: DWORD): BOOL; stdcall; external cLibName name 'DdeSetUserHandle';
function DdeUnaccessData(Data: THDDEData): BOOL; stdcall; external cLibName name 'DdeUnaccessData';
function DdeUninitialize(Inst: DWORD): BOOL; stdcall; external cLibName name 'DdeUninitialize';
function DefDlgProc(hDlg: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefDlgProcA';
function DefDlgProcW(hDlg: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefDlgProcW';
function DefFrameProc(hWnd, hWndMDIClient: THWND; uMsg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefFrameProcA';
function DefFrameProcW(hWnd, hWndMDIClient: THWND; uMsg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefFrameProcW';
function DefMDIChildProc(hWnd: THWND; uMsg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefMDIChildProcA';
function DefMDIChildProcW(hWnd: THWND; uMsg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefMDIChildProcW';
function DefWindowProc(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefWindowProcA';
function DefWindowProcW(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'DefWindowProcW';
function DeferWindowPos(hWinPosInfo: THDWP; hWnd: THWND; hWndInsertAfter: THWND; x, y, cx, cy: Integer; uFlags: UINT): THDWP; stdcall; external cLibName name 'DeferWindowPos';
function DeleteMenu(hMenu: THMENU; uPosition, uFlags: UINT): BOOL; stdcall; external cLibName name 'DeleteMenu';
function DestroyAcceleratorTable(hAccel: THACCEL): BOOL; stdcall; external cLibName name 'DestroyAcceleratorTable';
function DestroyCaret: BOOL; stdcall; external cLibName name 'DestroyCaret';
function DestroyCursor(hCursor: THICON): BOOL; stdcall; external cLibName name 'DestroyCursor';
function DestroyIcon(hIcon: THICON): BOOL; stdcall; external cLibName name 'DestroyIcon';
function DestroyMenu(hMenu: THMENU): BOOL; stdcall; external cLibName name 'DestroyMenu';
function DestroyWindow(hWnd: THWND): BOOL; stdcall; external cLibName name 'DestroyWindow';
function DialogBoxIndirectParam(hInstance: THINST; const lpDialogTemplate: TDlgTemplate; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): Integer; stdcall; external cLibName name 'DialogBoxIndirectParamA';
function DialogBoxIndirectParamW(hInstance: THINST; const lpDialogTemplate: TDlgTemplate; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): Integer; stdcall; external cLibName name 'DialogBoxIndirectParamW';
function DialogBoxParam(hInstance: THINST; lpTemplateName: PAnsiChar; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): Integer; stdcall; external cLibName name 'DialogBoxParamA';
function DialogBoxParamW(hInstance: THINST; lpTemplateName: PWideChar; hWndParent: THWND; lpDialogFunc: TDlgProc; dwInitParam: TLPARAM): Integer; stdcall; external cLibName name 'DialogBoxParamW';
function DispatchMessage(const lpMsg: TMsg): Longint; stdcall; external cLibName name 'DispatchMessageA';
function DispatchMessageW(const lpMsg: TMsg): Longint; stdcall; external cLibName name 'DispatchMessageW';
function DlgDirList(hDlg: THWND; lpPathSpec: PAnsiChar; nIDListBox, nIDStaticPath: Integer; uFileType: UINT): Integer; stdcall; external cLibName name 'DlgDirListA';
function DlgDirListComboBox(hDlg: THWND; lpPathSpec: PAnsiChar; nIDComboBox, nIDStaticPath: Integer; uFiletype: UINT): Integer; stdcall; external cLibName name 'DlgDirListComboBoxA';
function DlgDirListComboBoxW(hDlg: THWND; lpPathSpec: PWideChar; nIDComboBox, nIDStaticPath: Integer; uFiletype: UINT): Integer; stdcall; external cLibName name 'DlgDirListComboBoxW';
function DlgDirListW(hDlg: THWND; lpPathSpec: PWideChar; nIDListBox, nIDStaticPath: Integer; uFileType: UINT): Integer; stdcall; external cLibName name 'DlgDirListW';
function DlgDirSelectComboBoxEx(hDlg: THWND; lpString: PAnsiChar; nCount, nIDComboBox: Integer): BOOL; stdcall; external cLibName name 'DlgDirSelectComboBoxExA';
function DlgDirSelectComboBoxExW(hDlg: THWND; lpString: PWideChar; nCount, nIDComboBox: Integer): BOOL; stdcall; external cLibName name 'DlgDirSelectComboBoxExW';
function DlgDirSelectEx(hDlg: THWND; lpString: PAnsiChar; nCount, nIDListBox: Integer): BOOL; stdcall; external cLibName name 'DlgDirSelectExA';
function DlgDirSelectExW(hDlg: THWND; lpString: PWideChar; nCount, nIDListBox: Integer): BOOL; stdcall; external cLibName name 'DlgDirSelectExW';
function DragDetect(p1: THWND; p2: TPoint): BOOL; stdcall; external cLibName name 'DragDetect';
function DragObject(p1, p2: THWND; p3: UINT; p4: DWORD; p5: THICON): DWORD; stdcall; external cLibName name 'DragObject';
function DrawAnimatedRects(hwnd: THWND; idAni: Integer; const lprcFrom, lprcTo: TRect): BOOL; stdcall; external cLibName name 'DrawAnimatedRects';
function DrawCaption(p1: THWND; p2: THDC; const p3: TRect; p4: UINT): BOOL; stdcall; external cLibName name 'DrawCaption';
function DrawEdge(hdc: THDC; var qrc: TRect; edge: UINT; grfFlags: UINT): BOOL; stdcall; external cLibName name 'DrawEdge';
function DrawFocusRect(hDC: THDC; const lprc: TRect): BOOL; stdcall; external cLibName name 'DrawFocusRect';
function DrawFrameControl(DC: THDC; const Rect: TRect; uType, uState: UINT): BOOL; stdcall; external cLibName name 'DrawFrameControl';
function DrawIcon(hDC: THDC; X, Y: Integer; hIcon: THICON): BOOL; stdcall; external cLibName name 'DrawIcon';
function DrawIconEx(hdc: THDC; xLeft, yTop: Integer; hIcon: THICON; cxWidth, cyWidth: Integer; istepIfAniCur: UINT; hbrFlickerFreeDraw: THBRUSH; diFlags: UINT): BOOL; stdcall; external cLibName name 'DrawIconEx';
function DrawMenuBar(hWnd: THWND): BOOL; stdcall; external cLibName name 'DrawMenuBar';
function DrawState(DC: THDC; p2: THBRUSH; p3: TDrawStateProc; p4: TLPARAM; p5: TWPARAM; p6, p7, p8, p9: Integer; p10: UINT): BOOL; stdcall; external cLibName name 'DrawStateA';
function DrawStateW(DC: THDC; p2: THBRUSH; p3: TDrawStateProc; p4: TLPARAM; p5: TWPARAM; p6, p7, p8, p9: Integer; p10: UINT): BOOL; stdcall; external cLibName name 'DrawStateW';
function DrawText(hDC: THDC; lpString: PAnsiChar; nCount: Integer; var lpRect: TRect; uFormat: UINT): Integer; stdcall; external cLibName name 'DrawTextA';
function DrawTextEx(DC: THDC; lpchText: PAnsiChar; cchText: Integer; var p4: TRect; dwDTFormat: UINT; DTParams: PDrawTextParams): Integer; stdcall; external cLibName name 'DrawTextExA';
function DrawTextExW(DC: THDC; lpchText: PWideChar; cchText: Integer; var p4: TRect; dwDTFormat: UINT; DTParams: PDrawTextParams): Integer; stdcall; external cLibName name 'DrawTextExW';
function DrawTextW(hDC: THDC; lpString: PWideChar; nCount: Integer; var lpRect: TRect; uFormat: UINT): Integer; stdcall; external cLibName name 'DrawTextW';
function EmptyClipboard: BOOL; stdcall; external cLibName name 'EmptyClipboard';
function EnableMenuItem(hMenu: THMENU; uIDEnableItem, uEnable: UINT): BOOL; stdcall; external cLibName name 'EnableMenuItem';
function EnableScrollBar(hWnd: THWND; wSBflags, wArrows: UINT): BOOL; stdcall; external cLibName name 'EnableScrollBar';
function EnableWindow(hWnd: THWND; bEnable: BOOL): BOOL; stdcall; external cLibName name 'EnableWindow';
function EndDeferWindowPos(hWinPosInfo: THDWP): BOOL; stdcall; external cLibName name 'EndDeferWindowPos';
function EndDialog(hDlg: THWND; nResult: Integer): BOOL; stdcall; external cLibName name 'EndDialog';
function EndMenu: BOOL; stdcall; external cLibName name 'EndMenu';
function EndPaint(hWnd: THWND; const lpPaint: TPaintStruct): BOOL; stdcall; external cLibName name 'EndPaint';
function EnumChildWindows(hWndParent: THWND; lpEnumFunc: TWndEnumProc; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumChildWindows';
function EnumClipboardFormats(format: UINT): UINT; stdcall; external cLibName name 'EnumClipboardFormats';
function EnumDesktopWindows(hDesktop: THDESK; lpfn: TWndEnumProc; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumDesktopWindows';
function EnumDesktops(hwinsta: THWINSTA; lpEnumFunc: TDeskTopEnumProcA; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumDesktopsA';
function EnumDesktopsW(hwinsta: THWINSTA; lpEnumFunc: TDeskTopEnumProcW; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumDesktopsW';
function EnumDisplayDevices(Unused: Pointer; iDevNum: DWORD; var lpDisplayDevice: TDisplayDeviceA; dwFlags: DWORD): BOOL; stdcall; external cLibName name 'EnumDisplayDevicesA';
function EnumDisplayDevicesW(Unused: Pointer; iDevNum: DWORD; var lpDisplayDevice: TDisplayDeviceW; dwFlags: DWORD): BOOL; stdcall; external cLibName name 'EnumDisplayDevicesW';
function EnumDisplaySettings(lpszDeviceName: PAnsiChar; iModeNum: DWORD; var lpDevMode: TDeviceModeA): BOOL; stdcall; external cLibName name 'EnumDisplaySettingsA';
function EnumDisplaySettingsW(lpszDeviceName: PWideChar; iModeNum: DWORD; var lpDevMode: TDeviceModeW): BOOL; stdcall; external cLibName name 'EnumDisplaySettingsW';
function EnumProps(hWnd: THWND; lpEnumFunc: TPropEnumProcA): Integer; stdcall; external cLibName name 'EnumPropsA';
function EnumPropsEx(hWnd: THWND; lpEnumFunc: TPropEnumProcExA; lParam: TLPARAM): Integer; stdcall; external cLibName name 'EnumPropsExA';
function EnumPropsExW(hWnd: THWND; lpEnumFunc: TPropEnumProcExW; lParam: TLPARAM): Integer; stdcall; external cLibName name 'EnumPropsExW';
function EnumPropsW(hWnd: THWND; lpEnumFunc: TPropEnumProcW): Integer; stdcall; external cLibName name 'EnumPropsW';
function EnumThreadWindows(dwThreadId: DWORD; lpfn: TWndEnumProc; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumThreadWindows';
function EnumWindowStations(lpEnumFunc: TEnumWinStatProcA; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumWindowStationsA';
function EnumWindowStationsW(lpEnumFunc: TEnumWinStatProcW; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumWindowStationsW';
function EnumWindows(lpEnumFunc: TWndEnumProc; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'EnumWindows';
function EqualRect(const lprc1, lprc2: TRect): BOOL; stdcall; external cLibName name 'EqualRect';
function ExcludeUpdateRgn(hDC: THDC; hWnd: THWND): Integer; stdcall; external cLibName name 'ExcludeUpdateRgn';
function ExitWindowsEx(uFlags: UINT; dwReserved: DWORD): BOOL; stdcall; external cLibName name 'ExitWindowsEx';
function FillRect(hDC: THDC; const lprc: TRect; hbr: THBRUSH): Integer; stdcall; external cLibName name 'FillRect';
function FindWindow(lpClassName, lpWindowName: PAnsiChar): THWND; stdcall; external cLibName name 'FindWindowA';
function FindWindowEx(Parent, Child: THWND; ClassName, WindowName: PAnsiChar): THWND; stdcall; external cLibName name 'FindWindowExA';
function FindWindowExW(Parent, Child: THWND; ClassName, WindowName: PWideChar): THWND; stdcall; external cLibName name 'FindWindowExW';
function FindWindowW(lpClassName, lpWindowName: PWideChar): THWND; stdcall; external cLibName name 'FindWindowW';
function FlashWindow(hWnd: THWND; bInvert: BOOL): BOOL; stdcall; external cLibName name 'FlashWindow';
function FlashWindowEx(var pfwi: TFlashWInfo): BOOL; stdcall; external cLibName name 'FlashWindowEx';
function FrameRect(hDC: THDC; const lprc: TRect; hbr: THBRUSH): Integer; stdcall; external cLibName name 'FrameRect';
function FreeDDElParam(msg: UINT; lParam: Longint): BOOL; stdcall; external cLibName name 'FreeDDElParam';
function GetActiveWindow: THWND; stdcall; external cLibName name 'GetActiveWindow';
function GetAltTabInfo(hwnd: THWND; iItem: Integer; var pati: TAltTabInfo; pszItemText: PAnsiChar; cchItemText: UINT): BOOL; stdcall; external cLibName name 'GetAltTabInfoA';
function GetAltTabInfoW(hwnd: THWND; iItem: Integer; var pati: TAltTabInfo; pszItemText: PWideChar; cchItemText: UINT): BOOL; stdcall; external cLibName name 'GetAltTabInfoW';
function GetAncestor(hwnd: THWND; gaFlags: UINT): THWND; stdcall; external cLibName name 'GetAncestor';
function GetAsyncKeyState(vKey: Integer): SHORT; stdcall; external cLibName name 'GetAsyncKeyState';
function GetCapture: THWND; stdcall; external cLibName name 'GetCapture';
function GetCaretBlinkTime: UINT; stdcall; external cLibName name 'GetCaretBlinkTime';
function GetCaretPos(var lpPoint: TPoint): BOOL; stdcall; external cLibName name 'GetCaretPos';
function GetClassInfo(hInstance: THINST; lpClassName: PAnsiChar; var lpWndClass: TWndClassA): BOOL; stdcall; external cLibName name 'GetClassInfoA';
function GetClassInfoEx(Instance: THINST; Classname: PAnsiChar; var WndClass: TWndClassExA): BOOL; stdcall; external cLibName name 'GetClassInfoExA';
function GetClassInfoExW(Instance: THINST; Classname: PWideChar; var WndClass: TWndClassExW): BOOL; stdcall; external cLibName name 'GetClassInfoExW';
function GetClassInfoW(hInstance: THINST; lpClassName: PWideChar; var lpWndClass: TWndClassW): BOOL; stdcall; external cLibName name 'GetClassInfoW';
function GetClassLong(hWnd: THWND; nIndex: Integer): DWORD; stdcall; external cLibName name 'GetClassLongA';
function GetClassLongW(hWnd: THWND; nIndex: Integer): DWORD; stdcall; external cLibName name 'GetClassLongW';
function GetClassName(hWnd: THWND; lpClassName: PAnsiChar; nMaxCount: Integer): Integer; stdcall; external cLibName name 'GetClassNameA';
function GetClassNameW(hWnd: THWND; lpClassName: PWideChar; nMaxCount: Integer): Integer; stdcall; external cLibName name 'GetClassNameW';
function GetClassWord(hWnd: THWND; nIndex: Integer): Word; stdcall; external cLibName name 'GetClassWord';
function GetClientRect(hWnd: THWND; var lpRect: TRect): BOOL; stdcall; external cLibName name 'GetClientRect';
function GetClipCursor(var lpRect: TRect): BOOL; stdcall; external cLibName name 'GetClipCursor';
function GetClipboardData(uFormat: UINT): THandle; stdcall; external cLibName name 'GetClipboardData';
function GetClipboardFormatName(format: UINT; lpszFormatName: PAnsiChar; cchMaxCount: Integer): Integer; stdcall; external cLibName name 'GetClipboardFormatNameA';
function GetClipboardFormatNameW(format: UINT; lpszFormatName: PWideChar; cchMaxCount: Integer): Integer; stdcall; external cLibName name 'GetClipboardFormatNameW';
function GetClipboardOwner: THWND; stdcall; external cLibName name 'GetClipboardOwner';
function GetClipboardSequenceNumber: DWORD; stdcall; external cLibName name 'GetClipboardSequenceNumber';
function GetClipboardViewer: THWND; stdcall; external cLibName name 'GetClipboardViewer';
function GetComboBoxInfo(hwndCombo: THWND; var pcbi: TComboBoxInfo): BOOL; stdcall; external cLibName name 'GetComboBoxInfo';
function GetCursor: THCURSOR; stdcall; external cLibName name 'GetCursor';
function GetCursorInfo(var pci: TCursorInfo): BOOL; stdcall; external cLibName name 'GetCursorInfo';
function GetCursorPos(var lpPoint: TPoint): BOOL; stdcall; external cLibName name 'GetCursorPos';
function GetDC(hWnd: THWND): THDC; stdcall; external cLibName name 'GetDC';
function GetDCEx(hWnd: THWND; hrgnClip: THRGN; flags: DWORD): THDC; stdcall; external cLibName name 'GetDCEx';
function GetDesktopWindow: THWND; stdcall; external cLibName name 'GetDesktopWindow';
function GetDialogBaseUnits: Longint; stdcall; external cLibName name 'GetDialogBaseUnits';
function GetDlgCtrlID(hWnd: THWND): Integer; stdcall; external cLibName name 'GetDlgCtrlID';
function GetDlgItem(hDlg: THWND; nIDDlgItem: Integer): THWND; stdcall; external cLibName name 'GetDlgItem';
function GetDlgItemInt(hDlg: THWND; nIDDlgItem: Integer; var lpTranslated: BOOL; bSigned: BOOL): UINT; stdcall; external cLibName name 'GetDlgItemInt';
function GetDlgItemText(hDlg: THWND; nIDDlgItem: Integer; lpString: PAnsiChar; nMaxCount: Integer): UINT; stdcall; external cLibName name 'GetDlgItemTextA';
function GetDlgItemTextW(hDlg: THWND; nIDDlgItem: Integer; lpString: PWideChar; nMaxCount: Integer): UINT; stdcall; external cLibName name 'GetDlgItemTextW';
function GetDoubleClickTime: UINT; stdcall; external cLibName name 'GetDoubleClickTime';
function GetFocus: THWND; stdcall; external cLibName name 'GetFocus';
function GetForegroundWindow: THWND; stdcall; external cLibName name 'GetForegroundWindow';
function GetGUIThreadInfo(idThread: DWORD; var pgui: TGUIThreadinfo): BOOL; stdcall; external cLibName name 'GetGUIThreadInfo';
function GetGuiResources(hProcess: THandle; uiFlags: DWORD): DWORD; stdcall; external cLibName name 'GetGuiResources';
function GetIconInfo(hIcon: THICON; var piconinfo: TIconInfo): BOOL; stdcall; external cLibName name 'GetIconInfo';
function GetInputState: BOOL; stdcall; external cLibName name 'GetInputState';
function GetKBCodePage: UINT; stdcall; external cLibName name 'GetKBCodePage';
function GetKeyNameText(lParam: Longint; lpString: PAnsiChar; nSize: Integer): Integer; stdcall; external cLibName name 'GetKeyNameTextA';
function GetKeyNameTextW(lParam: Longint; lpString: PWideChar; nSize: Integer): Integer; stdcall; external cLibName name 'GetKeyNameTextW';
function GetKeyState(nVirtKey: Integer): SHORT; stdcall; external cLibName name 'GetKeyState';
function GetKeyboardLayout(dwLayout: DWORD): THKL; stdcall; external cLibName name 'GetKeyboardLayout';
function GetKeyboardLayoutList(nBuff: Integer; var List): UINT; stdcall; external cLibName name 'GetKeyboardLayoutList';
function GetKeyboardLayoutName(pwszKLID: PAnsiChar): BOOL; stdcall; external cLibName name 'GetKeyboardLayoutNameA';
function GetKeyboardLayoutNameW(pwszKLID: PWideChar): BOOL; stdcall; external cLibName name 'GetKeyboardLayoutNameW';
function GetKeyboardState(var KeyState: uint8): BOOL; stdcall; external cLibName name 'GetKeyboardState';
function GetKeyboardType(nTypeFlag: Integer): Integer; stdcall; external cLibName name 'GetKeyboardType';
function GetLastActivePopup(hWnd: THWND): THWND; stdcall; external cLibName name 'GetLastActivePopup';
function GetLastInputInfo(var plii: TLastInputInfo): BOOL; stdcall; external cLibName name 'GetLastInputInfo';
function GetListBoxInfo(hwnd: THWND): DWORD; stdcall; external cLibName name 'GetListBoxInfo';
function GetMenu(hWnd: THWND): THMENU; stdcall; external cLibName name 'GetMenu';
function GetMenuBarInfo(hend: THWND; idObject, idItem: Longint; var pmbi: TMenuBarInfo): BOOL; stdcall; external cLibName name 'GetMenuBarInfo';
function GetMenuCheckMarkDimensions: Longint; stdcall; external cLibName name 'GetMenuCheckMarkDimensions';
function GetMenuContextHelpId(hMenu: THMENU): DWORD; stdcall; external cLibName name 'GetMenuContextHelpId';
function GetMenuDefaultItem(hMenu: THMENU; fByPos, gmdiFlags: UINT): UINT; stdcall; external cLibName name 'GetMenuDefaultItem';
function GetMenuInfo(hMenu: THMENU; var lpmi: TMenuInfo): BOOL; stdcall; external cLibName name 'GetMenuInfo';
function GetMenuItemCount(hMenu: THMENU): Integer; stdcall; external cLibName name 'GetMenuItemCount';
function GetMenuItemID(hMenu: THMENU; nPos: Integer): UINT; stdcall; external cLibName name 'GetMenuItemID';
function GetMenuItemInfo(p1: THMENU; p2: UINT; p3: BOOL; var p4: TMenuItemInfoA): BOOL; stdcall; external cLibName name 'GetMenuItemInfoA';
function GetMenuItemInfoW(p1: THMENU; p2: UINT; p3: BOOL; var p4: TMenuItemInfoW): BOOL; stdcall; external cLibName name 'GetMenuItemInfoW';
function GetMenuItemRect(hWnd: THWND; hMenu: THMENU; uItem: UINT; var lprcItem: TRect): BOOL; stdcall; external cLibName name 'GetMenuItemRect';
function GetMenuState(hMenu: THMENU; uId, uFlags: UINT): UINT; stdcall; external cLibName name 'GetMenuState';
function GetMenuString(hMenu: THMENU; uIDItem: UINT; lpString: PAnsiChar; nMaxCount: Integer; uFlag: UINT): Integer; stdcall; external cLibName name 'GetMenuStringA';
function GetMenuStringW(hMenu: THMENU; uIDItem: UINT; lpString: PWideChar; nMaxCount: Integer; uFlag: UINT): Integer; stdcall; external cLibName name 'GetMenuStringW';
function GetMessage(var lpMsg: TMsg; hWnd: THWND; wMsgFilterMin, wMsgFilterMax: UINT): BOOL; stdcall; external cLibName name 'GetMessageA';
function GetMessageExtraInfo: Longint; stdcall; external cLibName name 'GetMessageExtraInfo';
function GetMessagePos: DWORD; stdcall; external cLibName name 'GetMessagePos';
function GetMessageTime: Longint; stdcall; external cLibName name 'GetMessageTime';
function GetMessageW(var lpMsg: TMsg; hWnd: THWND; wMsgFilterMin, wMsgFilterMax: UINT): BOOL; stdcall; external cLibName name 'GetMessageW';
function GetNextDlgGroupItem(hDlg: THWND; hCtl: THWND; bPrevious: BOOL): THWND; stdcall; external cLibName name 'GetNextDlgGroupItem';
function GetNextDlgTabItem(hDlg: THWND; hCtl: THWND; bPrevious: BOOL): THWND; stdcall; external cLibName name 'GetNextDlgTabItem';
function GetOpenClipboardWindow: THWND; stdcall; external cLibName name 'GetOpenClipboardWindow';
function GetParent(hWnd: THWND): THWND; stdcall; external cLibName name 'GetParent';
function GetPriorityClipboardFormat(var paFormatPriorityList; cFormats: Integer): Integer; stdcall; external cLibName name 'GetPriorityClipboardFormat';
function GetProcessWindowStation: THWINSTA; stdcall; external cLibName name 'GetProcessWindowStation';
function GetProp(hWnd: THWND; lpString: PAnsiChar): THandle; stdcall; external cLibName name 'GetPropA';
function GetPropW(hWnd: THWND; lpString: PWideChar): THandle; stdcall; external cLibName name 'GetPropW';
function GetQueueStatus(flags: UINT): DWORD; stdcall; external cLibName name 'GetQueueStatus';
function GetScrollBarInfo(hwnd: THWND; idObject: Longint; var psbi: TScrollBarInfo): BOOL; stdcall; external cLibName name 'GetScrollBarInfo';
function GetScrollInfo(hWnd: THWND; BarFlag: Integer; var ScrollInfo: TScrollInfo): BOOL; stdcall; external cLibName name 'GetScrollInfo';
function GetScrollPos(hWnd: THWND; nBar: Integer): Integer; stdcall; external cLibName name 'GetScrollPos';
function GetScrollRange(hWnd: THWND; nBar: Integer; var lpMinPos, lpMaxPos: Integer): BOOL; stdcall; external cLibName name 'GetScrollRange';
function GetSubMenu(hMenu: THMENU; nPos: Integer): THMENU; stdcall; external cLibName name 'GetSubMenu';
function GetSysColor(nIndex: Integer): DWORD; stdcall; external cLibName name 'GetSysColor';
function GetSysColorBrush(nIndex: Integer): THBRUSH; stdcall; external cLibName name 'GetSysColorBrush';
function GetSystemMenu(hWnd: THWND; bRevert: BOOL): THMENU; stdcall; external cLibName name 'GetSystemMenu';
function GetSystemMetrics(nIndex: Integer): Integer; stdcall; external cLibName name 'GetSystemMetrics';
function GetTabbedTextExtent(hDC: THDC; lpString: PAnsiChar; nCount, nTabPositions: Integer; var lpnTabStopPositions): DWORD; stdcall; external cLibName name 'GetTabbedTextExtentA';
function GetTabbedTextExtentW(hDC: THDC; lpString: PWideChar; nCount, nTabPositions: Integer; var lpnTabStopPositions): DWORD; stdcall; external cLibName name 'GetTabbedTextExtentW';
function GetThreadDesktop(dwThreadId: DWORD): THDESK; stdcall; external cLibName name 'GetThreadDesktop';
function GetTopWindow(hWnd: THWND): THWND; stdcall; external cLibName name 'GetTopWindow';
function GetUpdateRect(hWnd: THWND; var lpRect: TRect; bErase: BOOL): BOOL; stdcall; external cLibName name 'GetUpdateRect';
function GetUpdateRgn(hWnd: THWND; hRgn: THRGN; bErase: BOOL): Integer; stdcall; external cLibName name 'GetUpdateRgn';
function GetUserObjectInformation(hObj: THandle; nIndex: Integer; pvInfo: Pointer; nLength: DWORD; var lpnLengthNeeded: DWORD): BOOL; stdcall; external cLibName name 'GetUserObjectInformationA';
function GetUserObjectInformationW(hObj: THandle; nIndex: Integer; pvInfo: Pointer; nLength: DWORD; var lpnLengthNeeded: DWORD): BOOL; stdcall; external cLibName name 'GetUserObjectInformationW';
function GetUserObjectSecurity(hObj: THandle; var pSIRequested: DWORD; pSID: PSecurityDescriptor; nLength: DWORD; var lpnLengthNeeded: DWORD): BOOL; stdcall; external cLibName name 'GetUserObjectSecurity';
function GetWindow(hWnd: THWND; uCmd: UINT): THWND; stdcall; external cLibName name 'GetWindow';
function GetWindowContextHelpId(hWnd: THWND): DWORD; stdcall; external cLibName name 'GetWindowContextHelpId';
function GetWindowDC(hWnd: THWND): THDC; stdcall; external cLibName name 'GetWindowDC';
function GetWindowInfo(hwnd: THWND; var pwi: TWindowInfo): BOOL; stdcall; external cLibName name 'GetWindowInfo';
function GetWindowLong(hWnd: THWND; nIndex: Integer): Longint; stdcall; external cLibName name 'GetWindowLongA';
function GetWindowLongW(hWnd: THWND; nIndex: Integer): Longint; stdcall; external cLibName name 'GetWindowLongW';
function GetWindowModuleFileName(hwnd: THWND; pszFileName: PAnsiChar; cchFileNameMax: UINT): UINT; stdcall; external cLibName name 'GetWindowModuleFileNameA';
function GetWindowModuleFileNameW(hwnd: THWND; pszFileName: PAnsiChar; cchFileNameMax: UINT): UINT; stdcall; external cLibName name 'GetWindowModuleFileNameW';
function GetWindowPlacement(hWnd: THWND; WindowPlacement: PWindowPlacement): BOOL; stdcall; external cLibName name 'GetWindowPlacement';
function GetWindowRect(hWnd: THWND; var lpRect: TRect): BOOL; stdcall; external cLibName name 'GetWindowRect';
function GetWindowRgn(hWnd: THWND; hRgn: THRGN): Integer; stdcall; external cLibName name 'GetWindowRgn';
function GetWindowText(hWnd: THWND; lpString: PAnsiChar; nMaxCount: Integer): Integer; stdcall; external cLibName name 'GetWindowTextA';
function GetWindowTextLength(hWnd: THWND): Integer; stdcall; external cLibName name 'GetWindowTextLengthA';
function GetWindowTextLengthW(hWnd: THWND): Integer; stdcall; external cLibName name 'GetWindowTextLengthW';
function GetWindowTextW(hWnd: THWND; lpString: PWideChar; nMaxCount: Integer): Integer; stdcall; external cLibName name 'GetWindowTextW';
function GetWindowThreadProcessId(hWnd: THWND; lpdwProcessId: Pointer): DWORD; stdcall; external cLibName name 'GetWindowThreadProcessId';
function GetWindowWord(hWnd: THWND; nIndex: Integer): Word; stdcall; external cLibName name 'GetWindowWord';
function GrayString(hDC: THDC; hBrush: THBRUSH; lpOutputFunc: TOutputProc; lpData: TLPARAM; nCount, X, Y, nWidth, nHeight: Integer): BOOL; stdcall; external cLibName name 'GrayStringA';
function GrayStringW(hDC: THDC; hBrush: THBRUSH; lpOutputFunc: TOutputProc; lpData: TLPARAM; nCount, X, Y, nWidth, nHeight: Integer): BOOL; stdcall; external cLibName name 'GrayStringW';
function HideCaret(hWnd: THWND): BOOL; stdcall; external cLibName name 'HideCaret';
function HiliteMenuItem(hWnd: THWND; hMenu: THMENU; uIDHiliteItem: UINT; uHilite: UINT): BOOL; stdcall; external cLibName name 'HiliteMenuItem';
function ImpersonateDdeClientWindow(hWndClient: THWND; hWndServer: THWND): BOOL; stdcall; external cLibName name 'ImpersonateDdeClientWindow';
function InSendMessage: BOOL; stdcall; external cLibName name 'InSendMessage';
function InSendMessageeX(lpReserved: Pointer): DWORD; stdcall; external cLibName name 'InSendMessageeX';
function InflateRect(var lprc: TRect; dx, dy: Integer): BOOL; stdcall; external cLibName name 'InflateRect';
function InsertMenu(hMenu: THMENU; uPosition, uFlags, uIDNewItem: UINT; lpNewItem: PAnsiChar): BOOL; stdcall; external cLibName name 'InsertMenuA';
function InsertMenuItem(p1: THMENU; p2: UINT; p3: BOOL; const p4: TMenuItemInfoA): BOOL; stdcall; external cLibName name 'InsertMenuItemA';
function InsertMenuItemW(p1: THMENU; p2: UINT; p3: BOOL; const p4: TMenuItemInfoW): BOOL; stdcall; external cLibName name 'InsertMenuItemW';
function InsertMenuW(hMenu: THMENU; uPosition, uFlags, uIDNewItem: UINT; lpNewItem: PWideChar): BOOL; stdcall; external cLibName name 'InsertMenuW';
function IntersectRect(var lprcDst: TRect; const lprcSrc1, lprcSrc2: TRect): BOOL; stdcall; external cLibName name 'IntersectRect';
function InvalidateRect(hWnd: THWND; lpRect: PRect; bErase: BOOL): BOOL; stdcall; external cLibName name 'InvalidateRect';
function InvalidateRgn(hWnd: THWND; hRgn: THRGN; bErase: BOOL): BOOL; stdcall; external cLibName name 'InvalidateRgn';
function InvertRect(hDC: THDC; const lprc: TRect): BOOL; stdcall; external cLibName name 'InvertRect';
function IsCharAlpha(ch: AnsiChar): BOOL; stdcall; external cLibName name 'IsCharAlphaA';
function IsCharAlphaNumeric(ch: AnsiChar): BOOL; stdcall; external cLibName name 'IsCharAlphaNumericA';
function IsCharAlphaNumericW(ch: WideChar): BOOL; stdcall; external cLibName name 'IsCharAlphaNumericW';
function IsCharAlphaW(ch: WideChar): BOOL; stdcall; external cLibName name 'IsCharAlphaW';
function IsCharLower(ch: AnsiChar): BOOL; stdcall; external cLibName name 'IsCharLowerA';
function IsCharLowerW(ch: WideChar): BOOL; stdcall; external cLibName name 'IsCharLowerW';
function IsCharUpper(ch: AnsiChar): BOOL; stdcall; external cLibName name 'IsCharUpperA';
function IsCharUpperW(ch: WideChar): BOOL; stdcall; external cLibName name 'IsCharUpperW';
function IsChild(hWndParent, hWnd: THWND): BOOL; stdcall; external cLibName name 'IsChild';
function IsClipboardFormatAvailable(format: UINT): BOOL; stdcall; external cLibName name 'IsClipboardFormatAvailable';
function IsDialogMessage(hDlg: THWND; var lpMsg: TMsg): BOOL; stdcall; external cLibName name 'IsDialogMessageA';
function IsDialogMessageW(hDlg: THWND; var lpMsg: TMsg): BOOL; stdcall; external cLibName name 'IsDialogMessageW';
function IsDlgButtonChecked(hDlg: THWND; nIDButton: Integer): UINT; stdcall;external cLibName name 'IsDlgButtonChecked';
function IsIconic(hWnd: THWND): BOOL; stdcall; external cLibName name 'IsIconic';
function IsMenu(hMenu: THMENU): BOOL; stdcall; external cLibName name 'IsMenu';
function IsRectEmpty(const lprc: TRect): BOOL; stdcall; external cLibName name 'IsRectEmpty';
function IsWindow(hWnd: THWND): BOOL; stdcall; external cLibName name 'IsWindow';
function IsWindowEnabled(hWnd: THWND): BOOL; stdcall; external cLibName name 'IsWindowEnabled';
function IsWindowUnicode(hWnd: THWND): BOOL; stdcall; external cLibName name 'IsWindowUnicode';
function IsWindowVisible(hWnd: THWND): BOOL; stdcall; external cLibName name 'IsWindowVisible';
function IsZoomed(hWnd: THWND): BOOL; stdcall; external cLibName name 'IsZoomed';
function KillTimer(hWnd: THWND; uIDEvent: UINT): BOOL; stdcall; external cLibName name 'KillTimer';
function LoadAccelerators(hInstance: THINST; lpTableName: PAnsiChar): THACCEL; stdcall; external cLibName name 'LoadAcceleratorsA';
function LoadAcceleratorsW(hInstance: THINST; lpTableName: PWideChar): THACCEL; stdcall; external cLibName name 'LoadAcceleratorsW';
function LoadBitmap(hInstance: THINST; lpBitmapName: PAnsiChar): THBITMAP; stdcall; external cLibName name 'LoadBitmapA';
function LoadBitmapW(THINSTance: THINST; lpBitmapName: PAnsiChar): THBITMAP; stdcall; external cLibName name 'LoadBitmapW';
function LoadCursor(THINSTance: THINST; lpCursorName: PAnsiChar): THCURSOR; stdcall; external cLibName name 'LoadCursorA';
function LoadCursorFromFile(lpFileName: PAnsiChar): THCURSOR; stdcall; external cLibName name 'LoadCursorFromFileA';
function LoadCursorFromFileW(lpFileName: PAnsiChar): THCURSOR; stdcall; external cLibName name 'LoadCursorFromFileW';
function LoadCursorW(THINSTance: THINST; lpCursorName: PWideChar): THCURSOR; stdcall; external cLibName name 'LoadCursorW';
function LoadIcon(THINSTance: THINST; lpIconName: PAnsiChar): THICON; stdcall; external cLibName name 'LoadIconA';
function LoadIconW(THINSTance: THINST; lpIconName: PWideChar): THICON; stdcall; external cLibName name 'LoadIconW';
function LoadImage(THINST: THINST; ImageName: PAnsiChar; ImageType: UINT; X, Y: Integer; Flags: UINT): THandle; stdcall; external cLibName name 'LoadImageA';
function LoadImageW(THINST: THINST; ImageName: PWideChar; ImageType: UINT; X, Y: Integer; Flags: UINT): THandle; stdcall; external cLibName name 'LoadImageW';
function LoadKeyboardLayout(pwszKLID: PAnsiChar; Flags: UINT): THKL; stdcall; external cLibName name 'LoadKeyboardLayoutA';
function LoadKeyboardLayoutW(pwszKLID: PWideChar; Flags: UINT): THKL; stdcall; external cLibName name 'LoadKeyboardLayoutW';
function LoadMenu(THINSTance: THINST; lpMenuName: PAnsiChar): THMENU; stdcall; external cLibName name 'LoadMenuA';
function LoadMenuIndirect(lpMenuTemplate: Pointer): THMENU; stdcall; external cLibName name 'LoadMenuIndirectA';
function LoadMenuIndirectW(lpMenuTemplate: Pointer): THMENU; stdcall; external cLibName name 'LoadMenuIndirectW';
function LoadMenuW(THINSTance: THINST; lpMenuName: PAnsiChar): THMENU; stdcall; external cLibName name 'LoadMenuW';
function LoadString(THINSTance: THINST; uID: UINT; lpBuffer: PAnsiChar; nBufferMax: Integer): Integer; stdcall; external cLibName name 'LoadStringA';
function LoadStringW(THINSTance: THINST; uID: UINT; lpBuffer: PWideChar; nBufferMax: Integer): Integer; stdcall; external cLibName name 'LoadStringW';
function LockWindowUpdate(hWndLock: THWND): BOOL; stdcall; external cLibName name 'LockWindowUpdate';
function LockWorkStation: BOOL; stdcall; external cLibName name 'LockWorkStation';
function LookupIconIdFromDirectory(presbits: PByte; fIcon: BOOL): Integer; stdcall; external cLibName name 'LookupIconIdFromDirectory';
function LookupIconIdFromDirectoryEx(presbits: PByte; fIcon: BOOL; cxDesired, cyDesired: Integer; Flags: UINT): Integer; stdcall; external cLibName name 'LookupIconIdFromDirectoryEx';
function MapDialogRect(hDlg: THWND; var lpRect: TRect): BOOL; stdcall; external cLibName name 'MapDialogRect';
function MapVirtualKey(uCode, uMapType: UINT): UINT; stdcall; external cLibName name 'MapVirtualKeyA';
function MapVirtualKeyEx(uCode, uMapType: UINT; dwhkl: THKL): UINT; stdcall; external cLibName name 'MapVirtualKeyExA';
function MapVirtualKeyExW(uCode, uMapType: UINT; dwhkl: THKL): UINT; stdcall; external cLibName name 'MapVirtualKeyExW';
function MapVirtualKeyW(uCode, uMapType: UINT): UINT; stdcall; external cLibName name 'MapVirtualKeyW';
function MapWindowPoints(hWndFrom, hWndTo: THWND; var lpPoints; cPoints: UINT): Integer; stdcall; external cLibName name 'MapWindowPoints';
function MenuItemFromPoint(hWnd: THWND; hMenu: THMENU; ptScreen: TPoint): BOOL; stdcall; external cLibName name 'MenuItemFromPoint';
function MessageBeep(uType: UINT): BOOL; stdcall; external cLibName name 'MessageBeep';
function MessageBox(hWnd: THWND; lpText, lpCaption: PAnsiChar; uType: UINT): Integer; stdcall; external cLibName name 'MessageBoxA';
function MessageBoxEx(hWnd: THWND; lpText, lpCaption: PAnsiChar; uType: UINT; wLanguageId: Word): Integer; stdcall; external cLibName name 'MessageBoxExA';
function MessageBoxExW(hWnd: THWND; lpText, lpCaption: PWideChar; uType: UINT; wLanguageId: Word): Integer; stdcall; external cLibName name 'MessageBoxExW';
function MessageBoxIndirect(const MsgBoxParams: TMsgBoxParamsA): BOOL; stdcall; external cLibName name 'MessageBoxIndirectA';
function MessageBoxIndirectW(const MsgBoxParams: TMsgBoxParamsW): BOOL; stdcall; external cLibName name 'MessageBoxIndirectW';
function MessageBoxW(hWnd: THWND; lpText, lpCaption: PWideChar; uType: UINT): Integer; stdcall; external cLibName name 'MessageBoxW';
function ModifyMenu(hMnu: THMENU; uPosition, uFlags, uIDNewItem: UINT; lpNewItem: PAnsiChar): BOOL; stdcall; external cLibName name 'ModifyMenuA';
function ModifyMenuW(hMnu: THMENU; uPosition, uFlags, uIDNewItem: UINT; lpNewItem: PWideChar): BOOL; stdcall; external cLibName name 'ModifyMenuW';
function MoveWindow(hWnd: THWND; X, Y, nWidth, nHeight: Integer; bRepaint: BOOL): BOOL; stdcall; external cLibName name 'MoveWindow';
function MsgWaitForMultipleObjects(nCount: DWORD; var pHandles; fWaitAll: BOOL; dwMilliseconds, dwWakeMask: DWORD): DWORD; stdcall; external cLibName name 'MsgWaitForMultipleObjects';
function MsgWaitForMultipleObjectsEx(nCount: DWORD; var pHandles; dwMilliseconds, dwWakeMask, dwFlags: DWORD): DWORD; stdcall; external cLibName name 'MsgWaitForMultipleObjectsEx';
procedure NotifyWinEvent(event: DWORD; hwnd: THWND; idObject, idChild: Longint); external cLibName name 'NotifyWinEvent';
function OemKeyScan(wOemChar: Word): DWORD; stdcall; external cLibName name 'OemKeyScan';
function OemToChar(lpszSrc: PAnsiChar; lpszDst: PAnsiChar): BOOL; stdcall; external cLibName name 'OemToCharA';
function OemToCharBuff(lpszSrc: PAnsiChar; lpszDst: PAnsiChar; cchDstLength: DWORD): BOOL; stdcall; external cLibName name 'OemToCharBuffA';
function OemToCharBuffW(lpszSrc: PWideChar; lpszDst: PWideChar; cchDstLength: DWORD): BOOL; stdcall; external cLibName name 'OemToCharBuffW';
function OemToCharW(lpszSrc: PWideChar; lpszDst: PWideChar): BOOL; stdcall; external cLibName name 'OemToCharW';
function OffsetRect(var lprc: TRect; dx, dy: Integer): BOOL; stdcall; external cLibName name 'OffsetRect';
function OpenClipboard(hWndNewOwner: THWND): BOOL; stdcall; external cLibName name 'OpenClipboard';
function OpenDesktop(lpszDesktop: PAnsiChar; dwFlags: DWORD; fInherit: BOOL; dwDesiredAccess: DWORD): THDESK; stdcall; external cLibName name 'OpenDesktopA';
function OpenDesktopW(lpszDesktop: PWideChar; dwFlags: DWORD; fInherit: BOOL; dwDesiredAccess: DWORD): THDESK; stdcall; external cLibName name 'OpenDesktopW';
function OpenIcon(hWnd: THWND): BOOL; stdcall; external cLibName name 'OpenIcon';
function OpenInputDesktop(dwFlags: DWORD; fInherit: BOOL; dwDesiredAccess: DWORD): THDESK; stdcall; external cLibName name 'OpenInputDesktop';
function OpenWindowStation(lpszWinSta: PAnsiChar; fInherit: BOOL; dwDesiredAccess: DWORD): THWINSTA; stdcall; external cLibName name 'OpenWindowStationA';
function OpenWindowStationW(lpszWinSta: PWideChar; fInherit: BOOL; dwDesiredAccess: DWORD): THWINSTA; stdcall; external cLibName name 'OpenWindowStationW';
function PackDDElParam(msg: UINT; uiLo: UINT; uiHi: UINT): Longint; stdcall; external cLibName name 'PackDDElParam';
function PaintDesktop(hdc: THDC): BOOL; stdcall; external cLibName name 'PaintDesktop';
function PeekMessage(var lpMsg: TMsg; hWnd: THWND; wMsgFilterMin, wMsgFilterMax, wRemoveMsg: UINT): BOOL; stdcall; external cLibName name 'PeekMessageA';
function PeekMessageW(var lpMsg: TMsg; hWnd: THWND; wMsgFilterMin, wMsgFilterMax, wRemoveMsg: UINT): BOOL; stdcall; external cLibName name 'PeekMessageW';
function PostMessage(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'PostMessageA';
function PostMessageW(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'PostMessageW';
procedure PostQuitMessage(nExitCode: Integer); stdcall; external cLibName name 'PostQuitMessage';
function PostThreadMessage(idThread: DWORD; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'PostThreadMessageA';
function PostThreadMessageW(idThread: DWORD; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'PostThreadMessageW';
function PtInRect(const lprc: TRect; pt: TPoint): BOOL; stdcall; external cLibName name 'PtInRect';
function RealChildWindowFromPoint(hwndParent: THWND; ptParentClientCoords: TPoint): THWND; stdcall; external cLibName name 'RealChildWindowFromPoint';
function RealGetWindowClass(hwnd: THWND; pszType: PAnsiChar; cchType: UINT): UINT; stdcall; external cLibName name 'RealGetWindowClassA';
function RealGetWindowClassW(hwnd: THWND; pszType: PWideChar; cchType: UINT): UINT; stdcall; external cLibName name 'RealGetWindowClassW';
function RedrawWindow(hWnd: THWND; lprcUpdate: PRect; hrgnUpdate: THRGN; flags: UINT): BOOL; stdcall; external cLibName name 'RedrawWindow';
function RegisterClass(const lpWndClass: TWndClassA): TATOM; stdcall; external cLibName name 'RegisterClassA';
function RegisterClassEx(const WndClass: TWndClassExA): TATOM; stdcall; external cLibName name 'RegisterClassExA';
function RegisterClassExW(const WndClass: TWndClassExW): TATOM; stdcall; external cLibName name 'RegisterClassExW';
function RegisterClassW(const lpWndClass: TWndClassW): TATOM; stdcall; external cLibName name 'RegisterClassW';
function RegisterClipboardFormat(lpszFormat: PAnsiChar): UINT; stdcall; external cLibName name 'RegisterClipboardFormatA';
function RegisterClipboardFormatW(lpszFormat: PWideChar): UINT; stdcall; external cLibName name 'RegisterClipboardFormatW';
function RegisterDeviceNotification(hRecipient: THandle; NotificationFilter: Pointer; Flags: DWORD): HDEVNOTIFY; stdcall; external cLibName name 'RegisterDeviceNotificationA';
function RegisterDeviceNotificationW(hRecipient: THandle; NotificationFilter: Pointer; Flags: DWORD): HDEVNOTIFY; stdcall; external cLibName name 'RegisterDeviceNotificationW';
function RegisterHotKey(hWnd: THWND; id: Integer; fsModifiers, vk: UINT): BOOL; stdcall; external cLibName name 'RegisterHotKey';
function RegisterWindowMessage(lpString: PAnsiChar): UINT; stdcall; external cLibName name 'RegisterWindowMessageA';
function RegisterWindowMessageW(lpString: PWideChar): UINT; stdcall; external cLibName name 'RegisterWindowMessageW';
function ReleaseCapture: BOOL; stdcall; external cLibName name 'ReleaseCapture';
function ReleaseDC(hWnd: THWND; hDC: THDC): Integer; stdcall; external cLibName name 'ReleaseDC';
function RemoveMenu(hMenu: THMENU; uPosition, uFlags: UINT): BOOL; stdcall; external cLibName name 'RemoveMenu';
function RemoveProp(hWnd: THWND; lpString: PAnsiChar): THandle; stdcall; external cLibName name 'RemovePropA';
function RemovePropW(hWnd: THWND; lpString: PWideChar): THandle; stdcall; external cLibName name 'RemovePropW';
function ReplyMessage(lResult: TLRESULT): BOOL; stdcall; external cLibName name 'ReplyMessage';
function ReuseDDElParam(lParam: Longint; msgIn: UINT; msgOut: UINT; uiLo: UINT; uiHi: UINT): Longint; stdcall; external cLibName name 'ReuseDDElParam';
function ScreenToClient(hWnd: THWND; var lpPoint: TPoint): BOOL; stdcall; external cLibName name 'ScreenToClient';
function ScrollDC(DC: THDC; DX, DY: Integer; var Scroll, Clip: TRect; Rgn: THRGN; Update: PRect): BOOL; stdcall; external cLibName name 'ScrollDC';
function ScrollWindow(hWnd: THWND; XAmount, YAmount: Integer; Rect, ClipRect: PRect): BOOL; stdcall; external cLibName name 'ScrollWindow';
function ScrollWindowEx(hWnd: THWND; dx, dy: Integer; prcScroll, prcClip: PRect; hrgnUpdate: THRGN; prcUpdate: PRect; flags: UINT): BOOL; stdcall; external cLibName name 'ScrollWindowEx';
function SendDlgItemMessage(hDlg: THWND; nIDDlgItem: Integer; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): Longint; stdcall; external cLibName name 'SendDlgItemMessageA';
function SendDlgItemMessageW(hDlg: THWND; nIDDlgItem: Integer; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): Longint; stdcall; external cLibName name 'SendDlgItemMessageW';
function SendInput(cInputs: UINT; var pInputs: TInput; cbSize: Integer): UINT; stdcall; external cLibName name 'SendInput';
function SendMessage(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'SendMessageA';
function SendMessageCallback(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM; lpResultCallBack: TSendASyncProc; dwData: DWORD): BOOL; stdcall; external cLibName name 'SendMessageCallbackA';
function SendMessageCallbackW(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM; lpResultCallBack: TSendASyncProc; dwData: DWORD): BOOL; stdcall; external cLibName name 'SendMessageCallbackW';
function SendMessageTimeout(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM; fuFlags, uTimeout: UINT; var lpdwResult: DWORD): TLRESULT; stdcall; external cLibName name 'SendMessageTimeoutA';
function SendMessageTimeoutW(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM; fuFlags, uTimeout: UINT; var lpdwResult: DWORD): TLRESULT; stdcall; external cLibName name 'SendMessageTimeoutW';
function SendMessageW(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): TLRESULT; stdcall; external cLibName name 'SendMessageW';
function SendNotifyMessage(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'SendNotifyMessageA';
function SendNotifyMessageW(hWnd: THWND; Msg: UINT; wParam: TWPARAM; lParam: TLPARAM): BOOL; stdcall; external cLibName name 'SendNotifyMessageW';
function SetActiveWindow(hWnd: THWND): THWND; stdcall; external cLibName name 'SetActiveWindow';
function SetCapture(hWnd: THWND): THWND; stdcall; external cLibName name 'SetCapture';
function SetCaretBlinkTime(uMSeconds: UINT): BOOL; stdcall; external cLibName name 'SetCaretBlinkTime';
function SetCaretPos(X, Y: Integer): BOOL; stdcall; external cLibName name 'SetCaretPos';
function SetClassLong(hWnd: THWND; nIndex: Integer; dwNewLong: Longint): DWORD; stdcall; external cLibName name 'SetClassLongA';
function SetClassLongW(hWnd: THWND; nIndex: Integer; dwNewLong: Longint): DWORD; stdcall; external cLibName name 'SetClassLongW';
function SetClassWord(hWnd: THWND; nIndex: Integer; wNewWord: Word): Word; stdcall; external cLibName name 'SetClassWord';
function SetClipboardData(uFormat: UINT; hMem: THandle): THandle; stdcall; external cLibName name 'SetClipboardData';
function SetClipboardViewer(hWndNewViewer: THWND): THWND; stdcall; external cLibName name 'SetClipboardViewer';
function SetCursor(hCursor: THICON): THCURSOR; stdcall; external cLibName name 'SetCursor';
function SetCursorPos(X, Y: Integer): BOOL; stdcall; external cLibName name 'SetCursorPos';
procedure SetDebugErrorLevel(dwLevel: DWORD); stdcall; external cLibName name 'SetDebugErrorLevel';
function SetDlgItemInt(hDlg: THWND; nIDDlgItem: Integer; uValue: UINT; bSigned: BOOL): BOOL; stdcall; external cLibName name 'SetDlgItemInt';
function SetDlgItemText(hDlg: THWND; nIDDlgItem: Integer; lpString: PAnsiChar): BOOL; stdcall; external cLibName name 'SetDlgItemTextA';
function SetDlgItemTextW(hDlg: THWND; nIDDlgItem: Integer; lpString: PWideChar): BOOL; stdcall; external cLibName name 'SetDlgItemTextW';
function SetDoubleClickTime(Interval: UINT): BOOL; stdcall; external cLibName name 'SetDoubleClickTime';
function SetFocus(hWnd: THWND): THWND; stdcall; external cLibName name 'SetFocus';
function SetForegroundWindow(hWnd: THWND): BOOL; stdcall; external cLibName name 'SetForegroundWindow';
function SetKeyboardState(var KeyState: uint8): BOOL; stdcall; external cLibName name 'SetKeyboardState';
procedure SetLastErrorEx(dwErrCode, dwType: DWORD); stdcall; external cLibName name 'SetLastErrorEx';
function SetMenu(hWnd: THWND; hMenu: THMENU): BOOL; stdcall; external cLibName name 'SetMenu';
function SetMenuContextHelpId(hMenu: THMENU; HelpID: DWORD): BOOL; stdcall; external cLibName name 'SetMenuContextHelpId';
function SetMenuDefaultItem(hMenu: THMENU; uItem, fByPos: UINT): BOOL; stdcall; external cLibName name 'SetMenuDefaultItem';
function SetMenuInfo(hMenu: THMENU; const lpcmi: TMenuInfo): BOOL; stdcall; external cLibName name 'SetMenuInfo';
function SetMenuItemBitmaps(hMenu: THMENU; uPosition, uFlags: UINT; hBitmapUnchecked: THBITMAP; hBitmapChecked: THBITMAP): BOOL; stdcall; external cLibName name 'SetMenuItemBitmaps';
function SetMenuItemInfo(p1: THMENU; p2: UINT; p3: BOOL; const p4: TMenuItemInfoA): BOOL; stdcall; external cLibName name 'SetMenuItemInfoA';
function SetMenuItemInfoW(p1: THMENU; p2: UINT; p3: BOOL; const p4: TMenuItemInfoW): BOOL; stdcall; external cLibName name 'SetMenuItemInfoW';
function SetMessageExtraInfo(lParam: TLPARAM): TLPARAM; stdcall; external cLibName name 'SetMessageExtraInfo';
function SetMessageQueue(cMessagesMax: Integer): BOOL; stdcall; external cLibName name 'SetMessageQueue';
function SetParent(hWndChild, hWndNewParent: THWND): THWND; stdcall; external cLibName name 'SetParent';
function SetProcessWindowStation(hWinSta: THWINSTA): BOOL; stdcall; external cLibName name 'SetProcessWindowStation';
function SetProp(hWnd: THWND; lpString: PAnsiChar; hData: THandle): BOOL; stdcall; external cLibName name 'SetPropA';
function SetPropW(hWnd: THWND; lpString: PWideChar; hData: THandle): BOOL; stdcall; external cLibName name 'SetPropW';
function SetRect(var lprc: TRect; xLeft, yTop, xRight, yBottom: Integer): BOOL; stdcall; external cLibName name 'SetRect';
function SetRectEmpty(var lprc: TRect): BOOL; stdcall; external cLibName name 'SetRectEmpty';
function SetScrollInfo(hWnd: THWND; BarFlag: Integer; const ScrollInfo: TScrollInfo; Redraw: BOOL): Integer; stdcall; external cLibName name 'SetScrollInfo';
function SetScrollPos(hWnd: THWND; nBar, nPos: Integer; bRedraw: BOOL): Integer; stdcall; external cLibName name 'SetScrollPos';
function SetScrollRange(hWnd: THWND; nBar, nMinPos, nMaxPos: Integer; bRedraw: BOOL): BOOL; stdcall; external cLibName name 'SetScrollRange';
function SetSysColors(cElements: Integer; const lpaElements; const lpaRgbValues): BOOL; stdcall; external cLibName name 'SetSysColors';
function SetSystemCursor(hcur: THICON; id: DWORD): BOOL; stdcall; external cLibName name 'SetSystemCursor';
function SetThreadDesktop(hDesktop: THDESK): BOOL; stdcall; external cLibName name 'SetThreadDesktop';
function SetTimer(hWnd: THWND; nIDEvent, uElapse: UINT; lpTimerFunc: TTimerProc): UINT; stdcall; external cLibName name 'SetTimer';
function SetUserObjectInformation(hObj: THandle; nIndex: Integer; pvInfo: Pointer; nLength: DWORD): BOOL; stdcall; external cLibName name 'SetUserObjectInformationA';
function SetUserObjectInformationW(hObj: THandle; nIndex: Integer; pvInfo: Pointer; nLength: DWORD): BOOL; stdcall; external cLibName name 'SetUserObjectInformationW';
function SetUserObjectSecurity(hObj: THandle; var pSIRequested: DWORD; pSID: PSecurityDescriptor): BOOL; stdcall; external cLibName name 'SetUserObjectSecurity';
function SetWinEventHook(eventMin, eventMax: DWORD; hmodWinEventProc: HMODULE; pfnWinEventProc: TWinEventProc; idProcess, idThread, dwFlags: DWORD): THandle; stdcall; external cLibName name 'SetWinEventHook';
function SetWindowContextHelpId(hWnd: THWND; HelpID: DWORD): BOOL; stdcall; external cLibName name 'SetWindowContextHelpId';
function SetWindowLong(hWnd: THWND; nIndex: Integer; dwNewLong: Longint): Longint; stdcall; external cLibName name 'SetWindowLongA';
function SetWindowLongW(hWnd: THWND; nIndex: Integer; dwNewLong: Longint): Longint; stdcall; external cLibName name 'SetWindowLongW';
function SetWindowPlacement(hWnd: THWND; WindowPlacement: PWindowPlacement): BOOL; stdcall; external cLibName name 'SetWindowPlacement';
function SetWindowPos(hWnd: THWND; hWndInsertAfter: THWND; X, Y, cx, cy: Integer; uFlags: UINT): BOOL; stdcall; external cLibName name 'SetWindowPos';
function SetWindowRgn(hWnd: THWND; hRgn: THRGN; bRedraw: BOOL): BOOL; stdcall; external cLibName name 'SetWindowRgn';
function SetWindowText(hWnd: THWND; lpString: PAnsiChar): BOOL; stdcall; external cLibName name 'SetWindowTextA';
function SetWindowTextW(hWnd: THWND; lpString: PWideChar): BOOL; stdcall; external cLibName name 'SetWindowTextW';
function SetWindowWord(hWnd: THWND; nIndex: Integer; wNewWord: Word): Word; stdcall; external cLibName name 'SetWindowWord';
function SetWindowsHook(nFilterType: Integer; pfnFilterProc: THookProc): THHOOK; stdcall; external cLibName name 'SetWindowsHookA';
function SetWindowsHookEx(idHook: Integer; lpfn: THookProc; hmod: THINST; dwThreadId: DWORD): THHOOK; stdcall; external cLibName name 'SetWindowsHookExA';
function SetWindowsHookExW(idHook: Integer; lpfn: THookProc; hmod: THINST; dwThreadId: DWORD): THHOOK; stdcall; external cLibName name 'SetWindowsHookExW';
function SetWindowsHookW(nFilterType: Integer; pfnFilterProc: THookProc): THHOOK; stdcall; external cLibName name 'SetWindowsHookW';
function ShowCaret(hWnd: THWND): BOOL; stdcall; external cLibName name 'ShowCaret';
function ShowCursor(bShow: BOOL): Integer; stdcall; external cLibName name 'ShowCursor';
function ShowOwnedPopups(hWnd: THWND; fShow: BOOL): BOOL; stdcall; external cLibName name 'ShowOwnedPopups';
function ShowScrollBar(hWnd: THWND; wBar: Integer; bShow: BOOL): BOOL; stdcall; external cLibName name 'ShowScrollBar';
function ShowWindow(hWnd: THWND; nCmdShow: Integer): BOOL; stdcall; external cLibName name 'ShowWindow';
function ShowWindowAsync(hWnd: THWND; nCmdShow: Integer): BOOL; stdcall; external cLibName name 'ShowWindowAsync';
function SubtractRect(var lprcDst: TRect; const lprcSrc1, lprcSrc2: TRect): BOOL; stdcall; external cLibName name 'SubtractRect';
function SwapMouseButton(fSwap: BOOL): BOOL; stdcall; external cLibName name 'SwapMouseButton';
function SwitchDesktop(hDesktop: THDESK): BOOL; stdcall; external cLibName name 'SwitchDesktop';
function SystemParametersInfo(uiAction, uiParam: UINT; pvParam: Pointer; fWinIni: UINT): BOOL; stdcall; external cLibName name 'SystemParametersInfoA';
function SystemParametersInfoW(uiAction, uiParam: UINT; pvParam: Pointer; fWinIni: UINT): BOOL; stdcall; external cLibName name 'SystemParametersInfoW';
function TabbedTextOut(hDC: THDC; X, Y: Integer; lpString: PAnsiChar; nCount, nTabPositions: Integer; var lpnTabStopPositions; nTabOrigin: Integer): Longint; stdcall; external cLibName name 'TabbedTextOutA';
function TabbedTextOutW(hDC: THDC; X, Y: Integer; lpString: PWideChar; nCount, nTabPositions: Integer; var lpnTabStopPositions; nTabOrigin: Integer): Longint; stdcall; external cLibName name 'TabbedTextOutW';
function TileWindows(hwndParent: THWND; wHow: UINT; lpRect: PRect; cKids: UINT; lpKids: Pointer): Word; stdcall; external cLibName name 'TileWindows';
function ToAscii(uVirtKey, uScanCode: UINT; const KeyState: uint8; lpChar: PChar; uFlags: UINT): Integer; stdcall; external cLibName name 'ToAscii';
function ToAsciiEx(uVirtKey: UINT; uScanCode: UINT; const KeyState: uint8; lpChar: PChar; uFlags: UINT; dwhkl: THKL): Integer; stdcall; external cLibName name 'ToAsciiEx';
function ToUnicode(wVirtKey, wScanCode: UINT; const KeyState: uint8; var pwszBuff; cchBuff: Integer; wFlags: UINT): Integer; stdcall; external cLibName name 'ToUnicode';
function ToUnicodeEx(wVirtKey, wScanCode: UINT; lpKeyState: PByte; pwszBuff: PWideChar; cchBuff: Integer; wFlags: UINT; dwhkl: THKL): Integer; stdcall; external cLibName name 'ToUnicodeEx';
function TrackMouseEvent(var EventTrack: TTrackMouseEvent): BOOL; stdcall; external cLibName name 'TrackMouseEvent';
function TrackPopupMenu(hMenu: THMENU; uFlags: UINT; x, y, nReserved: Integer; hWnd: THWND; prcRect: PRect): BOOL; stdcall; external cLibName name 'TrackPopupMenu';
function TrackPopupMenuEx(hMenu: THMENU; Flags: UINT; x, y: Integer; Wnd: THWND; TPMParams: PTPMParams): BOOL; stdcall; external cLibName name 'TrackPopupMenuEx';
function TranslateAccelerator(hWnd: THWND; hAccTable: THACCEL; var lpMsg: TMsg): Integer; stdcall; external cLibName name 'TranslateAcceleratorA';
function TranslateAcceleratorW(hWnd: THWND; hAccTable: THACCEL; var lpMsg: TMsg): Integer; stdcall; external cLibName name 'TranslateAcceleratorW';
function TranslateMDISysAccel(hWndClient: THWND; const lpMsg: TMsg): BOOL; stdcall; external cLibName name 'TranslateMDISysAccel';
function TranslateMessage(const lpMsg: TMsg): BOOL; stdcall; external cLibName name 'TranslateMessage';
function UnhookWinEvent(hWinEventHook: THandle): BOOL; stdcall; external cLibName name 'UnhookWinEvent';
function UnhookWindowsHook(nCode: Integer; pfnFilterProc: THookProc): BOOL; stdcall; external cLibName name 'UnhookWindowsHook';
function UnhookWindowsHookEx(hhk: THHOOK): BOOL; stdcall; external cLibName name 'UnhookWindowsHookEx';
function UnionRect(var lprcDst: TRect; const lprcSrc1, lprcSrc2: TRect): BOOL; stdcall; external cLibName name 'UnionRect';
function UnloadKeyboardLayout(hkl: THKL): BOOL; stdcall; external cLibName name 'UnloadKeyboardLayout';
function UnpackDDElParam(msg: UINT; lParam: Longint; puiLo: PUINT; puiHi: PUINT): BOOL; stdcall; external cLibName name 'UnpackDDElParam';
function UnregisterClass(lpClassName: PAnsiChar; THINSTance: THINST): BOOL; stdcall; external cLibName name 'UnregisterClassA';
function UnregisterClassW(lpClassName: PWideChar; THINSTance: THINST): BOOL; stdcall; external cLibName name 'UnregisterClassW';
function UnregisterDeviceNotification(Handle: HDEVNOTIFY): BOOL; stdcall; external cLibName name 'UnregisterDeviceNotification';
function UnregisterHotKey(hWnd: THWND; id: Integer): BOOL; stdcall; external cLibName name 'UnregisterHotKey';
function UpdateWindow(hWnd: THWND): BOOL; stdcall; external cLibName name 'UpdateWindow';
function UserHandleGrantAccess(hUserHandle, hJob: THandle): BOOL; stdcall; external cLibName name 'UserHandleGrantAccess';
function ValidateRect(hWnd: THWND; lpRect: PRect): BOOL; stdcall; external cLibName name 'ValidateRect';
function ValidateRgn(hWnd: THWND; hRgn: THRGN): BOOL; stdcall; external cLibName name 'ValidateRgn';
function VkKeyScan(ch: AnsiChar): SHORT; stdcall; external cLibName name 'VkKeyScanA';
function VkKeyScanEx(ch: AnsiChar; dwhkl: THKL): SHORT; stdcall; external cLibName name 'VkKeyScanExA';
function VkKeyScanExW(ch: WideChar; dwhkl: THKL): SHORT; stdcall; external cLibName name 'VkKeyScanExW';
function VkKeyScanW(ch: WideChar): SHORT; stdcall; external cLibName name 'VkKeyScanW';
function WaitForInputIdle(hProcess: THandle; dwMilliseconds: DWORD): DWORD; stdcall; external cLibName name 'WaitForInputIdle';
function WaitMessage: BOOL; stdcall; external cLibName name 'WaitMessage';
function WinHelp(hWndMain: THWND; lpszHelp: PAnsiChar; uCommand: UINT; dwData: DWORD): BOOL; stdcall; external cLibName name 'WinHelpA';
function WinHelpW(hWndMain: THWND; lpszHelp: PWideChar; uCommand: UINT; dwData: DWORD): BOOL; stdcall; external cLibName name 'WinHelpW';
function WindowFromDC(hDC: THDC): THWND; stdcall; external cLibName name 'WindowFromDC';
function WindowFromPoint(Point: TPoint): THWND; stdcall; external cLibName name 'WindowFromPoint';
procedure keybd_event(bVk: Byte; bScan: Byte; dwFlags, dwExtraInfo: DWORD); stdcall; external cLibName name 'keybd_event';
procedure mouse_event(dwFlags, dx, dy, dwData, dwExtraInfo: DWORD); stdcall; external cLibName name 'mouse_event';
function wsprintf(Output: PAnsiChar; Format: PAnsiChar): Integer; stdcall; external cLibName name 'wsprintfA';
function wsprintfW(Output: PWideChar; Format: PWideChar): Integer; stdcall; external cLibName name 'wsprintfW';
function wvsprintf(Output: PAnsiChar; Format: PAnsiChar; arglist: va_list): Integer; stdcall; external cLibName name 'wvsprintfA';
function wvsprintfW(Output: PWideChar; Format: PWideChar; arglist: va_list): Integer; stdcall; external cLibName name 'wvsprintfW';

{$endif}
implementation

end.


